# -*- coding: utf-8 -*-
"""CSE431.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17DqaDKOctvqz19D5QPvpUSJ1O4COdBub
"""

import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import numpy as np 
import pandas as pd

df=pd.read_csv('/content/go_emotions_dataset.csv')
df.head()

"""# New Section"""

df.isnull().sum().reset_index()

df.drop('id', inplace=True, axis=1)
df1 =df.iloc[:,2:-6]
df1.head()

plt.figure(figsize=(25,20))
sns.heatmap(df1.corr(), center=0, annot=True)

positive_col = ['admiration','amusement','approval','caring','curiosity','excitement','gratitude','joy','love','optimism','relief','surprise']
negative_col = ['sadness','pride','fear','embarrassment','disapproval','disappointment','confusion','annoyance','anger','nervousness','desire']
ambiguous_col = ['remorse','realization','grief','disgust']
neutral_col = ['neutral']
positive_col = df[positive_col]
negative_col = df[negative_col]
ambiguous_col = df[ambiguous_col]
neutral_col = df[neutral_col]

emotion_counts = {}
for c in positive_col:
    emotion_counts[c]  = positive_col[c].value_counts().to_dict()[1]
plt.figure(figsize = (20,20) )
fig = px.bar(x=list(emotion_counts.keys()), y=list(emotion_counts.values()))
fig.update_layout(title = 'Go Emotions', height = 600, xaxis_title=" Positive Emotion", yaxis_title="Number of Texts")
fig.show()

emotion_counts = {}
for c in negative_col:
    emotion_counts[c]  = negative_col[c].value_counts().to_dict()[1]
plt.figure(figsize = (20,20) )
fig = px.bar(x=list(emotion_counts.keys()), y=list(emotion_counts.values()))
fig.update_layout(title = 'Go Emotions', height = 600, xaxis_title="Negative Emotion", yaxis_title="Number of Texts")
fig.show()

df1 =df['example_very_unclear'].value_counts()
plt.figure(figsize = (5,5))
plt.pie(df1,labels = ['No','Yes'],autopct='%.0f%%' , radius = 2 ,explode = (0.1,0.03),shadow = True)
plt.show()